### ISSUE TITLE
PyPI package?

### ISSUE THREAD

**Issue by jonathandean** [airbrake/airbrake-django#2]
Warning: I'm very much a Python/Django noob

Any chance of making a PyPI package for this? http://pypi.python.org/pypi

I'd like to use this on a site deployed on Heroku and from what I can tell it needs to use pip to install it by placing it in requirements.txt in the django app. I'm happy to do the work if you'd like. I've never done it but it seems you can use setup to create a manifest and a package that you upload at http://pypi.python.org/pypi (Something like ```python setup.py sdist``` http://guide.python-distribute.org/creation.html) I just didn't want to try this myself and end up owning the package on PyPI since I'm not sure if you can transfer them to another owner later.

Love to discuss why or why not to do this.

Thanks!

**Comment by kyrylo** [comment]
This will be resolved once we merge this repo with airbrake-python. https://github.com/airbrake/airbrake-python/issues

airbrake-python is available on PyPI.
